import Head from "next/head";
import Image from "next/image";
import TableComp from "../components/Table/tableComp";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Crypto App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ margin: "auto" }}>
        <TableComp />
      </main>
    </div>
  );
}
