import Head from "next/head";
import TableComp from "../components/Table/tableComp";
import { useState, useEffect } from "react";
import Pagination from "@mui/material/Pagination";
import { Box } from "@mui/material";
import Loading from "../components/Loading/loading";
export default function Home({ data }) {
  const [coinData, setcoinData] = useState(data);
  const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    if (page === 1) setcoinData(data);
    else {
      setLoading(true);
      fetch(
        `https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=${page}&sparkline=false`
      )
        .then((res) => res.json())
        .then((data) => {
          setcoinData(data);
          setLoading(false);
        })
        .catch((error) => {
          console.error(error);
          setLoading(false);
        });
    }
  }, [page]);

  return (
    <>
      <Head>
        <title>Cryptocurrency App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/8/8b/Cryptocurrency_Logo.svg"
        />
      </Head>

      <main style={{ margin: "auto", marginBottom: "10%" }}>
        <TableComp data={coinData} />
        <Box sx={{ width: 345, margin: "auto", mt: 3 }}>
          <Pagination
            count={20}
            color="secondary"
            onChange={(event, value) => {
              setPage(value);
            }}
          />
        </Box>
      </main>
      <Loading open={loading} setOpen={setLoading} />
    </>
  );
}
export async function getStaticProps() {
  const res = await fetch(
    "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false"
  );
  const data = await res.json();
  return {
    props: {
      data,
    },
    revalidate: 43200,
  };
}
