import Head from "next/head";
import TableComp from "../components/Table/tableComp";
export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Crypto App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ margin: "auto" }}>
        <TableComp data={data} />
      </main>
    </div>
  );
}
export async function getStaticProps() {
  const res = await fetch(
    "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false"
  );
  const data = await res.json();
  return {
    props: {
      data,
    },
    revalidate: 43200,
  };
}
